

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Status : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Status entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Status()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Status(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Status> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Status.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Status.DetailsClass.GetValue(this, global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Status.DetailsClass.SetValue(this, global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Effect
        {
            get
            {
                return global::LightSwitchApplication.Status.DetailsClass.GetValue(this, global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties.Effect);
            }
            set
            {
                global::LightSwitchApplication.Status.DetailsClass.SetValue(this, global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties.Effect, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Effect_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Effect_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Effect_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Creature Creature
        {
            get
            {
                return global::LightSwitchApplication.Status.DetailsClass.GetValue(this, global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties.Creature);
            }
            set
            {
                global::LightSwitchApplication.Status.DetailsClass.SetValue(this, global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties.Creature, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Creature_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Creature_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Creature_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Status,
                global::LightSwitchApplication.Status.DetailsClass,
                global::LightSwitchApplication.Status.DetailsClass.IImplementation,
                global::LightSwitchApplication.Status.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass>.Entry
                __StatusEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass>.Entry(
                    global::LightSwitchApplication.Status.DetailsClass.__Status_CreateNew,
                    global::LightSwitchApplication.Status.DetailsClass.__Status_Created,
                    global::LightSwitchApplication.Status.DetailsClass.__Status_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Status __Status_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Status> es)
            {
                return new global::LightSwitchApplication.Status(es);
            }
            private static void __Status_Created(global::LightSwitchApplication.Status e)
            {
                e.Status_Created();
            }
            private static bool __Status_AllowSaveWithErrors(global::LightSwitchApplication.Status e)
            {
                bool result = false;
                e.Status_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Status.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, string> Effect
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties.Effect) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, global::LightSwitchApplication.Creature> Creature
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties.Creature) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, global::LightSwitchApplication.Creature>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Effect { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Creature { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Status.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, int>.Data> c, global::LightSwitchApplication.Status.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Status e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Status e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Status.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Status.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Status e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, string>.Entry
                    Effect = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, string>.Entry(
                        "Effect",
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Effect_Stub,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Effect_ComputeIsReadOnly,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Effect_Validate,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Effect_GetImplementationValue,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Effect_SetImplementationValue,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Effect_OnValueChanged);
                private static void _Effect_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Status.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, string>.Data> c, global::LightSwitchApplication.Status.DetailsClass d, object sf)
                {
                    c(d, ref d._Effect, sf);
                }
                private static bool _Effect_ComputeIsReadOnly(global::LightSwitchApplication.Status e)
                {
                    bool result = false;
                    e.Effect_IsReadOnly(ref result);
                    return result;
                }
                private static void _Effect_Validate(global::LightSwitchApplication.Status e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Effect_Validate(r);
                }
                private static string _Effect_GetImplementationValue(global::LightSwitchApplication.Status.DetailsClass d)
                {
                    return d.ImplementationEntity.Effect;
                }
                private static void _Effect_SetImplementationValue(global::LightSwitchApplication.Status.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Effect = v;
                }
                private static void _Effect_OnValueChanged(global::LightSwitchApplication.Status e)
                {
                    e.Effect_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, global::LightSwitchApplication.Creature>.Entry
                    Creature = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, global::LightSwitchApplication.Creature>.Entry(
                        "Creature",
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Creature_Stub,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Creature_ComputeIsReadOnly,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Creature_Validate,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Creature_GetCoreImplementationValue,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Creature_GetImplementationValue,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Creature_SetImplementationValue,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Creature_Refresh,
                        global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties._Creature_OnValueChanged);
                private static void _Creature_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Status.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, global::LightSwitchApplication.Creature>.Data> c, global::LightSwitchApplication.Status.DetailsClass d, object sf)
                {
                    c(d, ref d._Creature, sf);
                }
                private static bool _Creature_ComputeIsReadOnly(global::LightSwitchApplication.Status e)
                {
                    bool result = false;
                    e.Creature_IsReadOnly(ref result);
                    return result;
                }
                private static void _Creature_Validate(global::LightSwitchApplication.Status e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Creature_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Creature_GetCoreImplementationValue(global::LightSwitchApplication.Status.DetailsClass d)
                {
                    return d.ImplementationEntity.Creature;
                }
                private static global::LightSwitchApplication.Creature _Creature_GetImplementationValue(global::LightSwitchApplication.Status.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Creature, global::LightSwitchApplication.Creature.DetailsClass>(global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties.Creature, ref d._Creature);
                }
                private static void _Creature_SetImplementationValue(global::LightSwitchApplication.Status.DetailsClass d, global::LightSwitchApplication.Creature v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties.Creature, ref d._Creature, (i, ev) => i.Creature = ev, v);
                }
                private static void _Creature_Refresh(global::LightSwitchApplication.Status.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Status.DetailsClass.PropertySetProperties.Creature, ref d._Creature);
                }
                private static void _Creature_OnValueChanged(global::LightSwitchApplication.Status e)
                {
                    e.Creature_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, string>.Data _Effect;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Status, global::LightSwitchApplication.Status.DetailsClass, global::LightSwitchApplication.Creature>.Data _Creature;
            
        }
    
        #endregion
    }
    
    #endregion
}
