

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Encounter : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Encounter entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Encounter()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Encounter(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Encounter> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Encounter.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Encounter_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Encounter_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Encounter.DetailsClass.GetValue(this, global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Encounter.DetailsClass.SetValue(this, global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.Encounter.DetailsClass.GetValue(this, global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.Encounter.DetailsClass.SetValue(this, global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int TotalXP
        {
            get
            {
                return global::LightSwitchApplication.Encounter.DetailsClass.GetValue(this, global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties.TotalXP);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalXP_Compute(ref int result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalXP_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Creature> Creatures
        {
            get
            {
                return global::LightSwitchApplication.Encounter.DetailsClass.GetValue(this, global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties.Creatures);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Creature> CreaturesQuery
        {
            get
            {
                return global::LightSwitchApplication.Encounter.DetailsClass.GetQuery(this, global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties.Creatures);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Encounter,
                global::LightSwitchApplication.Encounter.DetailsClass,
                global::LightSwitchApplication.Encounter.DetailsClass.IImplementation,
                global::LightSwitchApplication.Encounter.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass>.Entry
                __EncounterEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass>.Entry(
                    global::LightSwitchApplication.Encounter.DetailsClass.__Encounter_CreateNew,
                    global::LightSwitchApplication.Encounter.DetailsClass.__Encounter_Created,
                    global::LightSwitchApplication.Encounter.DetailsClass.__Encounter_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Encounter __Encounter_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Encounter> es)
            {
                return new global::LightSwitchApplication.Encounter(es);
            }
            private static void __Encounter_Created(global::LightSwitchApplication.Encounter e)
            {
                e.Encounter_Created();
            }
            private static bool __Encounter_AllowSaveWithErrors(global::LightSwitchApplication.Encounter e)
            {
                bool result = false;
                e.Encounter_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Encounter.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, int> TotalXP
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties.TotalXP) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, global::LightSwitchApplication.Creature> Creatures
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties.Creatures) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, global::LightSwitchApplication.Creature>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Name { get; set; }
                new global::System.Collections.IEnumerable Creatures { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Encounter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, int>.Data> c, global::LightSwitchApplication.Encounter.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Encounter e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Encounter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Encounter.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Encounter.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Encounter e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Encounter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, string>.Data> c, global::LightSwitchApplication.Encounter.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.Encounter e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.Encounter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.Encounter.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.Encounter.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.Encounter e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, int>.Entry
                    TotalXP = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, int>.Entry(
                        "TotalXP",
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._TotalXP_Stub,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._TotalXP_Validate,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._TotalXP_ComputeValue);
                private static void _TotalXP_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Encounter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, int>.Data> c, global::LightSwitchApplication.Encounter.DetailsClass d, object sf)
                {
                    c(d, ref d._TotalXP, sf);
                }
                private static void _TotalXP_Validate(global::LightSwitchApplication.Encounter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TotalXP_Validate(r);
                }
                private static int _TotalXP_ComputeValue(global::LightSwitchApplication.Encounter e)
                {
                    int value = default(int);
                    e.TotalXP_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, global::LightSwitchApplication.Creature>.Entry
                    Creatures = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, global::LightSwitchApplication.Creature>.Entry(
                        "Creatures",
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Creatures_Stub,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Creatures_GetReferencedEntities,
                        global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties._Creatures_GetEntityCollection);
                private static void _Creatures_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Encounter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, global::LightSwitchApplication.Creature>.Data> c, global::LightSwitchApplication.Encounter.DetailsClass d, object sf)
                {
                    c(d, ref d._Creatures, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Creature> _Creatures_GetReferencedEntities(global::LightSwitchApplication.Encounter.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Creature, global::LightSwitchApplication.Creature.DetailsClass>(global::LightSwitchApplication.Encounter.DetailsClass.PropertySetProperties.Creatures, ref d._Creatures);
                }
                private static global::System.Collections.IEnumerable _Creatures_GetEntityCollection(global::LightSwitchApplication.Encounter.DetailsClass d)
                {
                    return d.ImplementationEntity.Creatures;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, int>.Data _TotalXP;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Encounter, global::LightSwitchApplication.Encounter.DetailsClass, global::LightSwitchApplication.Creature>.Data _Creatures;
            
        }
    
        #endregion
    }
    
    #endregion
}
