//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 4/15/2012 11:12:22 PM
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for ApplicationDataObjectContext in the schema.
    /// </summary>
    public partial class ApplicationDataObjectContext : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ApplicationDataObjectContext object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationDataObjectContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("LightSwitchApplication", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("LightSwitchApplication.Implementation", typeName.Substring(22)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Creatures in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Creature> Creatures
        {
            get
            {
                if ((this._Creatures == null))
                {
                    this._Creatures = base.CreateQuery<Creature>("Creatures");
                }
                return this._Creatures;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Creature> _Creatures;
        /// <summary>
        /// There are no comments for Powers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Power> Powers
        {
            get
            {
                if ((this._Powers == null))
                {
                    this._Powers = base.CreateQuery<Power>("Powers");
                }
                return this._Powers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Power> _Powers;
        /// <summary>
        /// There are no comments for Statuses in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Status> Statuses
        {
            get
            {
                if ((this._Statuses == null))
                {
                    this._Statuses = base.CreateQuery<Status>("Statuses");
                }
                return this._Statuses;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Status> _Statuses;
        /// <summary>
        /// There are no comments for Encounters in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Encounter> Encounters
        {
            get
            {
                if ((this._Encounters == null))
                {
                    this._Encounters = base.CreateQuery<Encounter>("Encounters");
                }
                return this._Encounters;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Encounter> _Encounters;
        /// <summary>
        /// There are no comments for Creatures in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCreatures(Creature creature)
        {
            base.AddObject("Creatures", creature);
        }
        /// <summary>
        /// There are no comments for Powers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPowers(Power power)
        {
            base.AddObject("Powers", power);
        }
        /// <summary>
        /// There are no comments for Statuses in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStatuses(Status status)
        {
            base.AddObject("Statuses", status);
        }
        /// <summary>
        /// There are no comments for Encounters in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEncounters(Encounter encounter)
        {
            base.AddObject("Encounters", encounter);
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Creature in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Creatures")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Creature : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Creature object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="initiative">Initial value of Initiative.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="index">Initial value of Index.</param>
        /// <param name="currentHP">Initial value of CurrentHP.</param>
        /// <param name="tempHP">Initial value of TempHP.</param>
        /// <param name="maxHP">Initial value of MaxHP.</param>
        /// <param name="armorClass">Initial value of ArmorClass.</param>
        /// <param name="reflex">Initial value of Reflex.</param>
        /// <param name="fortitude">Initial value of Fortitude.</param>
        /// <param name="will">Initial value of Will.</param>
        /// <param name="speed">Initial value of Speed.</param>
        /// <param name="encounter_Creature">Initial value of Encounter_Creature.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Creature CreateCreature(int ID, int initiative, string name, int index, int currentHP, int tempHP, int maxHP, string armorClass, string reflex, string fortitude, string will, int speed, int encounter_Creature)
        {
            Creature creature = new Creature();
            creature.Id = ID;
            creature.Initiative = initiative;
            creature.Name = name;
            creature.Index = index;
            creature.CurrentHP = currentHP;
            creature.TempHP = tempHP;
            creature.MaxHP = maxHP;
            creature.ArmorClass = armorClass;
            creature.Reflex = reflex;
            creature.Fortitude = fortitude;
            creature.Will = will;
            creature.Speed = speed;
            creature.Encounter_Creature = encounter_Creature;
            return creature;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Initiative in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Initiative
        {
            get
            {
                return this._Initiative;
            }
            set
            {
                this.OnInitiativeChanging(value);
                if (object.Equals(this.Initiative, value))
                {
                    return;
                }
                this._Initiative = value;
                this.OnInitiativeChanged();
                this.OnPropertyChanged("Initiative");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Initiative;
        partial void OnInitiativeChanging(int value);
        partial void OnInitiativeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                if (object.Equals(this.Name, value))
                {
                    return;
                }
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Index in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Index
        {
            get
            {
                return this._Index;
            }
            set
            {
                this.OnIndexChanging(value);
                if (object.Equals(this.Index, value))
                {
                    return;
                }
                this._Index = value;
                this.OnIndexChanged();
                this.OnPropertyChanged("Index");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Index;
        partial void OnIndexChanging(int value);
        partial void OnIndexChanged();
        /// <summary>
        /// There are no comments for Property CurrentHP in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CurrentHP
        {
            get
            {
                return this._CurrentHP;
            }
            set
            {
                this.OnCurrentHPChanging(value);
                if (object.Equals(this.CurrentHP, value))
                {
                    return;
                }
                this._CurrentHP = value;
                this.OnCurrentHPChanged();
                this.OnPropertyChanged("CurrentHP");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CurrentHP;
        partial void OnCurrentHPChanging(int value);
        partial void OnCurrentHPChanged();
        /// <summary>
        /// There are no comments for Property TempHP in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TempHP
        {
            get
            {
                return this._TempHP;
            }
            set
            {
                this.OnTempHPChanging(value);
                if (object.Equals(this.TempHP, value))
                {
                    return;
                }
                this._TempHP = value;
                this.OnTempHPChanged();
                this.OnPropertyChanged("TempHP");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TempHP;
        partial void OnTempHPChanging(int value);
        partial void OnTempHPChanged();
        /// <summary>
        /// There are no comments for Property MaxHP in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int MaxHP
        {
            get
            {
                return this._MaxHP;
            }
            set
            {
                this.OnMaxHPChanging(value);
                if (object.Equals(this.MaxHP, value))
                {
                    return;
                }
                this._MaxHP = value;
                this.OnMaxHPChanged();
                this.OnPropertyChanged("MaxHP");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _MaxHP;
        partial void OnMaxHPChanging(int value);
        partial void OnMaxHPChanged();
        /// <summary>
        /// There are no comments for Property XP in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> XP
        {
            get
            {
                return this._XP;
            }
            set
            {
                this.OnXPChanging(value);
                if (object.Equals(this.XP, value))
                {
                    return;
                }
                this._XP = value;
                this.OnXPChanged();
                this.OnPropertyChanged("XP");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _XP;
        partial void OnXPChanging(global::System.Nullable<int> value);
        partial void OnXPChanged();
        /// <summary>
        /// There are no comments for Property ArmorClass in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ArmorClass
        {
            get
            {
                return this._ArmorClass;
            }
            set
            {
                this.OnArmorClassChanging(value);
                if (object.Equals(this.ArmorClass, value))
                {
                    return;
                }
                this._ArmorClass = value;
                this.OnArmorClassChanged();
                this.OnPropertyChanged("ArmorClass");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ArmorClass;
        partial void OnArmorClassChanging(string value);
        partial void OnArmorClassChanged();
        /// <summary>
        /// There are no comments for Property Reflex in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Reflex
        {
            get
            {
                return this._Reflex;
            }
            set
            {
                this.OnReflexChanging(value);
                if (object.Equals(this.Reflex, value))
                {
                    return;
                }
                this._Reflex = value;
                this.OnReflexChanged();
                this.OnPropertyChanged("Reflex");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Reflex;
        partial void OnReflexChanging(string value);
        partial void OnReflexChanged();
        /// <summary>
        /// There are no comments for Property Fortitude in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Fortitude
        {
            get
            {
                return this._Fortitude;
            }
            set
            {
                this.OnFortitudeChanging(value);
                if (object.Equals(this.Fortitude, value))
                {
                    return;
                }
                this._Fortitude = value;
                this.OnFortitudeChanged();
                this.OnPropertyChanged("Fortitude");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Fortitude;
        partial void OnFortitudeChanging(string value);
        partial void OnFortitudeChanged();
        /// <summary>
        /// There are no comments for Property Will in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Will
        {
            get
            {
                return this._Will;
            }
            set
            {
                this.OnWillChanging(value);
                if (object.Equals(this.Will, value))
                {
                    return;
                }
                this._Will = value;
                this.OnWillChanged();
                this.OnPropertyChanged("Will");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Will;
        partial void OnWillChanging(string value);
        partial void OnWillChanged();
        /// <summary>
        /// There are no comments for Property Speed in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Speed
        {
            get
            {
                return this._Speed;
            }
            set
            {
                this.OnSpeedChanging(value);
                if (object.Equals(this.Speed, value))
                {
                    return;
                }
                this._Speed = value;
                this.OnSpeedChanged();
                this.OnPropertyChanged("Speed");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Speed;
        partial void OnSpeedChanging(int value);
        partial void OnSpeedChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                if (object.Equals(this.Notes, value))
                {
                    return;
                }
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property Encounter_Creature in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Encounter_Creature
        {
            get
            {
                return this._Encounter_Creature;
            }
            set
            {
                this.OnEncounter_CreatureChanging(value);
                if (object.Equals(this.Encounter_Creature, value))
                {
                    return;
                }
                this._Encounter_Creature = value;
                this.OnEncounter_CreatureChanged();
                this.OnPropertyChanged("Encounter_Creature");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Encounter_Creature;
        partial void OnEncounter_CreatureChanging(int value);
        partial void OnEncounter_CreatureChanged();
        /// <summary>
        /// There are no comments for Powers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Power> Powers
        {
            get
            {
                this.@__Powers.EnsureValueInitialized();
                return this._Powers;
            }
            set
            {
                this._Powers = value;
                this.OnPropertyChanged("Powers");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Power> _Powers = new global::System.Data.Services.Client.DataServiceCollection<Power>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Statuses in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Status> Statuses
        {
            get
            {
                this.@__Statuses.EnsureValueInitialized();
                return this._Statuses;
            }
            set
            {
                this._Statuses = value;
                this.OnPropertyChanged("Statuses");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Status> _Statuses = new global::System.Data.Services.Client.DataServiceCollection<Status>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Encounter in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Encounter Encounter
        {
            get
            {
                this.@__Encounter.EnsureValueInitialized();
                return this._Encounter;
            }
            set
            {
                Encounter previous = this.Encounter;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Encounter = null;
                    previous.Creatures.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Encounter_Creature = value.Id;
                    }
                    else
                    {
                        this.Encounter_Creature = default(int);
                    }
                }
                this._Encounter = value;
                this.@__Encounter.OnValueSet();
                if ((value != null))
                {
                    value.@__Creatures.Add(this);
                }
                this.___OnPropertyChanged("Encounter");
                this.OnPropertyChanged("Encounter");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Encounter _Encounter;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Power in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Powers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Power : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Power object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="kind">Initial value of Kind.</param>
        /// <param name="exhausted">Initial value of Exhausted.</param>
        /// <param name="power_Creature">Initial value of Power_Creature.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Power CreatePower(int ID, string name, int kind, bool exhausted, int power_Creature)
        {
            Power power = new Power();
            power.Id = ID;
            power.Name = name;
            power.Kind = kind;
            power.Exhausted = exhausted;
            power.Power_Creature = power_Creature;
            return power;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                if (object.Equals(this.Name, value))
                {
                    return;
                }
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Kind in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Kind
        {
            get
            {
                return this._Kind;
            }
            set
            {
                this.OnKindChanging(value);
                if (object.Equals(this.Kind, value))
                {
                    return;
                }
                this._Kind = value;
                this.OnKindChanged();
                this.OnPropertyChanged("Kind");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Kind;
        partial void OnKindChanging(int value);
        partial void OnKindChanged();
        /// <summary>
        /// There are no comments for Property Recharge in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Recharge
        {
            get
            {
                return this._Recharge;
            }
            set
            {
                this.OnRechargeChanging(value);
                if (object.Equals(this.Recharge, value))
                {
                    return;
                }
                this._Recharge = value;
                this.OnRechargeChanged();
                this.OnPropertyChanged("Recharge");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Recharge;
        partial void OnRechargeChanging(global::System.Nullable<int> value);
        partial void OnRechargeChanged();
        /// <summary>
        /// There are no comments for Property Exhausted in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Exhausted
        {
            get
            {
                return this._Exhausted;
            }
            set
            {
                this.OnExhaustedChanging(value);
                if (object.Equals(this.Exhausted, value))
                {
                    return;
                }
                this._Exhausted = value;
                this.OnExhaustedChanged();
                this.OnPropertyChanged("Exhausted");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Exhausted;
        partial void OnExhaustedChanging(bool value);
        partial void OnExhaustedChanged();
        /// <summary>
        /// There are no comments for Property Attack in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Attack
        {
            get
            {
                return this._Attack;
            }
            set
            {
                this.OnAttackChanging(value);
                if (object.Equals(this.Attack, value))
                {
                    return;
                }
                this._Attack = value;
                this.OnAttackChanged();
                this.OnPropertyChanged("Attack");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Attack;
        partial void OnAttackChanging(string value);
        partial void OnAttackChanged();
        /// <summary>
        /// There are no comments for Property Hit in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Hit
        {
            get
            {
                return this._Hit;
            }
            set
            {
                this.OnHitChanging(value);
                if (object.Equals(this.Hit, value))
                {
                    return;
                }
                this._Hit = value;
                this.OnHitChanged();
                this.OnPropertyChanged("Hit");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Hit;
        partial void OnHitChanging(string value);
        partial void OnHitChanged();
        /// <summary>
        /// There are no comments for Property Miss in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Miss
        {
            get
            {
                return this._Miss;
            }
            set
            {
                this.OnMissChanging(value);
                if (object.Equals(this.Miss, value))
                {
                    return;
                }
                this._Miss = value;
                this.OnMissChanged();
                this.OnPropertyChanged("Miss");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Miss;
        partial void OnMissChanging(string value);
        partial void OnMissChanged();
        /// <summary>
        /// There are no comments for Property Effect in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Effect
        {
            get
            {
                return this._Effect;
            }
            set
            {
                this.OnEffectChanging(value);
                if (object.Equals(this.Effect, value))
                {
                    return;
                }
                this._Effect = value;
                this.OnEffectChanged();
                this.OnPropertyChanged("Effect");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Effect;
        partial void OnEffectChanging(string value);
        partial void OnEffectChanged();
        /// <summary>
        /// There are no comments for Property Range in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Range
        {
            get
            {
                return this._Range;
            }
            set
            {
                this.OnRangeChanging(value);
                if (object.Equals(this.Range, value))
                {
                    return;
                }
                this._Range = value;
                this.OnRangeChanged();
                this.OnPropertyChanged("Range");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Range;
        partial void OnRangeChanging(string value);
        partial void OnRangeChanged();
        /// <summary>
        /// There are no comments for Property Trigger in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Trigger
        {
            get
            {
                return this._Trigger;
            }
            set
            {
                this.OnTriggerChanging(value);
                if (object.Equals(this.Trigger, value))
                {
                    return;
                }
                this._Trigger = value;
                this.OnTriggerChanged();
                this.OnPropertyChanged("Trigger");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Trigger;
        partial void OnTriggerChanging(string value);
        partial void OnTriggerChanged();
        /// <summary>
        /// There are no comments for Property Power_Creature in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Power_Creature
        {
            get
            {
                return this._Power_Creature;
            }
            set
            {
                this.OnPower_CreatureChanging(value);
                if (object.Equals(this.Power_Creature, value))
                {
                    return;
                }
                this._Power_Creature = value;
                this.OnPower_CreatureChanged();
                this.OnPropertyChanged("Power_Creature");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Power_Creature;
        partial void OnPower_CreatureChanging(int value);
        partial void OnPower_CreatureChanged();
        /// <summary>
        /// There are no comments for Creature in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Creature Creature
        {
            get
            {
                this.@__Creature.EnsureValueInitialized();
                return this._Creature;
            }
            set
            {
                Creature previous = this.Creature;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Creature = null;
                    previous.Powers.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Power_Creature = value.Id;
                    }
                    else
                    {
                        this.Power_Creature = default(int);
                    }
                }
                this._Creature = value;
                this.@__Creature.OnValueSet();
                if ((value != null))
                {
                    value.@__Powers.Add(this);
                }
                this.___OnPropertyChanged("Creature");
                this.OnPropertyChanged("Creature");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Creature _Creature;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Status in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Statuses")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Status : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Status object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="effect">Initial value of Effect.</param>
        /// <param name="status_Creature">Initial value of Status_Creature.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Status CreateStatus(int ID, string effect, int status_Creature)
        {
            Status status = new Status();
            status.Id = ID;
            status.Effect = effect;
            status.Status_Creature = status_Creature;
            return status;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Effect in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Effect
        {
            get
            {
                return this._Effect;
            }
            set
            {
                this.OnEffectChanging(value);
                if (object.Equals(this.Effect, value))
                {
                    return;
                }
                this._Effect = value;
                this.OnEffectChanged();
                this.OnPropertyChanged("Effect");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Effect;
        partial void OnEffectChanging(string value);
        partial void OnEffectChanged();
        /// <summary>
        /// There are no comments for Property Status_Creature in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Status_Creature
        {
            get
            {
                return this._Status_Creature;
            }
            set
            {
                this.OnStatus_CreatureChanging(value);
                if (object.Equals(this.Status_Creature, value))
                {
                    return;
                }
                this._Status_Creature = value;
                this.OnStatus_CreatureChanged();
                this.OnPropertyChanged("Status_Creature");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Status_Creature;
        partial void OnStatus_CreatureChanging(int value);
        partial void OnStatus_CreatureChanged();
        /// <summary>
        /// There are no comments for Creature in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Creature Creature
        {
            get
            {
                this.@__Creature.EnsureValueInitialized();
                return this._Creature;
            }
            set
            {
                Creature previous = this.Creature;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Creature = null;
                    previous.Statuses.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Status_Creature = value.Id;
                    }
                    else
                    {
                        this.Status_Creature = default(int);
                    }
                }
                this._Creature = value;
                this.@__Creature.OnValueSet();
                if ((value != null))
                {
                    value.@__Statuses.Add(this);
                }
                this.___OnPropertyChanged("Creature");
                this.OnPropertyChanged("Creature");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Creature _Creature;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Encounter in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Encounters")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Encounter : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Encounter object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Encounter CreateEncounter(int ID, string name)
        {
            Encounter encounter = new Encounter();
            encounter.Id = ID;
            encounter.Name = name;
            return encounter;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                if (object.Equals(this.Name, value))
                {
                    return;
                }
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Creatures in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Creature> Creatures
        {
            get
            {
                this.@__Creatures.EnsureValueInitialized();
                return this._Creatures;
            }
            set
            {
                this._Creatures = value;
                this.OnPropertyChanged("Creatures");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Creature> _Creatures = new global::System.Data.Services.Client.DataServiceCollection<Creature>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
