//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Creature
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Creature :
        global::LightSwitchApplication.Creature.DetailsClass.IImplementation
    {
        partial void OnEncounter_CreatureChanged()
        {
            this.___OnPropertyChanged("Encounter_Creature");
            this.___OnPropertyChanged("Encounter");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnInitiativeChanged()
        {
            this.___OnPropertyChanged("Initiative");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnIndexChanged()
        {
            this.___OnPropertyChanged("Index");
        }
        
        partial void OnCurrentHPChanged()
        {
            this.___OnPropertyChanged("CurrentHP");
        }
        
        partial void OnTempHPChanged()
        {
            this.___OnPropertyChanged("TempHP");
        }
        
        partial void OnMaxHPChanged()
        {
            this.___OnPropertyChanged("MaxHP");
        }
        
        partial void OnXPChanged()
        {
            this.___OnPropertyChanged("XP");
        }
        
        partial void OnArmorClassChanged()
        {
            this.___OnPropertyChanged("ArmorClass");
        }
        
        partial void OnReflexChanged()
        {
            this.___OnPropertyChanged("Reflex");
        }
        
        partial void OnFortitudeChanged()
        {
            this.___OnPropertyChanged("Fortitude");
        }
        
        partial void OnWillChanged()
        {
            this.___OnPropertyChanged("Will");
        }
        
        partial void OnSpeedChanged()
        {
            this.___OnPropertyChanged("Speed");
        }
        
        partial void OnNotesChanged()
        {
            this.___OnPropertyChanged("Notes");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Creature.DetailsClass.IImplementation.Powers
        {
            get
            {
                return this.Powers;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Power> __Powers
        {
            get
            {
                if (this.___Powers == null)
                {
                    this.___Powers = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Power>(
                        this,
                        "Powers",
                        () => this._Powers,
                        e => global::System.Object.Equals(e.Power_Creature, this.Id));
                }
                return this.___Powers;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Power> ___Powers;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Creature.DetailsClass.IImplementation.Statuses
        {
            get
            {
                return this.Statuses;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Status> __Statuses
        {
            get
            {
                if (this.___Statuses == null)
                {
                    this.___Statuses = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Status>(
                        this,
                        "Statuses",
                        () => this._Statuses,
                        e => global::System.Object.Equals(e.Status_Creature, this.Id));
                }
                return this.___Statuses;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Status> ___Statuses;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Creature.DetailsClass.IImplementation.Encounter
        {
            get
            {
                return this.Encounter;
            }
            set
            {
                this.Encounter = (global::LightSwitchApplication.Implementation.Encounter)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Encounter> __Encounter
        {
            get
            {
                if (this.___Encounter == null)
                {
                    this.___Encounter = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Encounter>(
                        this,
                        "Encounter",
                        new string[] { "Encounter_Creature" },
                        e => global::System.Object.Equals(e.Id, this.Encounter_Creature),
                        () => this._Encounter,
                        e => this._Encounter = e);
                }
                return this.___Encounter;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Encounter> ___Encounter;
        
    }
    #endregion
    
    #region Power
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Power :
        global::LightSwitchApplication.Power.DetailsClass.IImplementation
    {
        partial void OnPower_CreatureChanged()
        {
            this.___OnPropertyChanged("Power_Creature");
            this.___OnPropertyChanged("Creature");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnKindChanged()
        {
            this.___OnPropertyChanged("Kind");
        }
        
        partial void OnRechargeChanged()
        {
            this.___OnPropertyChanged("Recharge");
        }
        
        partial void OnExhaustedChanged()
        {
            this.___OnPropertyChanged("Exhausted");
        }
        
        partial void OnAttackChanged()
        {
            this.___OnPropertyChanged("Attack");
        }
        
        partial void OnHitChanged()
        {
            this.___OnPropertyChanged("Hit");
        }
        
        partial void OnMissChanged()
        {
            this.___OnPropertyChanged("Miss");
        }
        
        partial void OnEffectChanged()
        {
            this.___OnPropertyChanged("Effect");
        }
        
        partial void OnRangeChanged()
        {
            this.___OnPropertyChanged("Range");
        }
        
        partial void OnTriggerChanged()
        {
            this.___OnPropertyChanged("Trigger");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Power.DetailsClass.IImplementation.Creature
        {
            get
            {
                return this.Creature;
            }
            set
            {
                this.Creature = (global::LightSwitchApplication.Implementation.Creature)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Creature> __Creature
        {
            get
            {
                if (this.___Creature == null)
                {
                    this.___Creature = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Creature>(
                        this,
                        "Creature",
                        new string[] { "Power_Creature" },
                        e => global::System.Object.Equals(e.Id, this.Power_Creature),
                        () => this._Creature,
                        e => this._Creature = e);
                }
                return this.___Creature;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Creature> ___Creature;
        
    }
    #endregion
    
    #region Status
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Status :
        global::LightSwitchApplication.Status.DetailsClass.IImplementation
    {
        partial void OnStatus_CreatureChanged()
        {
            this.___OnPropertyChanged("Status_Creature");
            this.___OnPropertyChanged("Creature");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnEffectChanged()
        {
            this.___OnPropertyChanged("Effect");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Status.DetailsClass.IImplementation.Creature
        {
            get
            {
                return this.Creature;
            }
            set
            {
                this.Creature = (global::LightSwitchApplication.Implementation.Creature)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Creature> __Creature
        {
            get
            {
                if (this.___Creature == null)
                {
                    this.___Creature = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Creature>(
                        this,
                        "Creature",
                        new string[] { "Status_Creature" },
                        e => global::System.Object.Equals(e.Id, this.Status_Creature),
                        () => this._Creature,
                        e => this._Creature = e);
                }
                return this.___Creature;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Creature> ___Creature;
        
    }
    #endregion
    
    #region Encounter
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Encounter :
        global::LightSwitchApplication.Encounter.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Encounter.DetailsClass.IImplementation.Creatures
        {
            get
            {
                return this.Creatures;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Creature> __Creatures
        {
            get
            {
                if (this.___Creatures == null)
                {
                    this.___Creatures = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Creature>(
                        this,
                        "Creatures",
                        () => this._Creatures,
                        e => global::System.Object.Equals(e.Encounter_Creature, this.Id));
                }
                return this.___Creatures;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Creature> ___Creatures;
        
    }
    #endregion
    
    #region ApplicationDataObjectContext
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationDataObjectContext
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Creature))
            {
                return new global::LightSwitchApplication.Implementation.Creature();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Power))
            {
                return new global::LightSwitchApplication.Implementation.Power();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Status))
            {
                return new global::LightSwitchApplication.Implementation.Status();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Encounter))
            {
                return new global::LightSwitchApplication.Implementation.Encounter();
            }
            return null;
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataObjectContext(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Creature) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Creature);
            }
            if (typeof(global::LightSwitchApplication.Power) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Power);
            }
            if (typeof(global::LightSwitchApplication.Status) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Status);
            }
            if (typeof(global::LightSwitchApplication.Encounter) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Encounter);
            }
            return null;
        }
    }
}
